# Generated by Django 4.0.4 on 2022-07-16 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZubyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.IntegerField(unique=True, verbose_name='phone number')),
                ('email', models.EmailField(max_length=254)),
                ('activate', models.BooleanField(default=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_supervisor', models.BooleanField(default=False, null=True)),
                ('is_admin', models.BooleanField(default=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollectorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_for', models.DateField(auto_now=True)),
                ('total_order', models.PositiveIntegerField(default=0)),
                ('collected_order', models.PositiveIntegerField(default=0)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('collected_amount', models.PositiveIntegerField(default=0)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loanapp.collector')),
            ],
        ),
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.DateField()),
                ('address', models.TextField(blank=True, null=True)),
                ('job', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=None)),
                ('blocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(blank=True, default=0, null=True)),
                ('quota', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('interest_rate', models.IntegerField(blank=True, default=30, null=True)),
                ('request_date', models.DateField(auto_now_add=True, null=True)),
                ('accept', models.BooleanField(blank=True, default=False, null=True)),
                ('accept_date', models.DateField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, default=14, null=True)),
                ('paid', models.BooleanField(blank=True, default=False, null=True)),
                ('costumer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loanapp.costumer')),
            ],
        ),
        migrations.CreateModel(
            name='Loanstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='loanapp.collectorrecord')),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loanapp.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Loanhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('borrow_date', models.DateField()),
                ('paid_date', models.DateField()),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loanapp.costumer')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loanapp.loanstatus'),
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('job', models.CharField(blank=True, max_length=50, null=True)),
                ('id_card', models.ImageField(blank=True, null=True, upload_to=None)),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loanapp.costumer')),
            ],
        ),
        migrations.AddField(
            model_name='costumer',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loanapp.level'),
        ),
        migrations.AddField(
            model_name='costumer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Contactlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.JSONField()),
                ('costumer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='loanapp.costumer')),
            ],
        ),
        migrations.AddField(
            model_name='collector',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loanapp.supervisor'),
        ),
        migrations.AddField(
            model_name='collector',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Bankdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bvn', models.CharField(blank=True, max_length=100, null=True)),
                ('debit_card', models.CharField(blank=True, max_length=100, null=True)),
                ('costumer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loanapp.costumer')),
            ],
        ),
    ]
