# Generated by Django 3.1.5 on 2021-02-26 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.IntegerField(unique=True, verbose_name='phone number')),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.DateField()),
                ('address', models.TextField(blank=True, null=True)),
                ('job', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=None)),
                ('blocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(blank=True, default=0, null=True)),
                ('quota', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('otp', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loanhistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('borrow_date', models.DateField()),
                ('paid_date', models.DateField()),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loanapp.costumer')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('interest_rate', models.IntegerField(blank=True, default=30, null=True)),
                ('request_date', models.DateField(auto_now_add=True, null=True)),
                ('accept', models.BooleanField(blank=True, default=False, null=True)),
                ('accept_date', models.DateField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, default=14, null=True)),
                ('paid', models.BooleanField(blank=True, default=False, null=True)),
                ('costumer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loanapp.costumer')),
            ],
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('job', models.CharField(blank=True, max_length=50, null=True)),
                ('id_card', models.ImageField(blank=True, null=True, upload_to=None)),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loanapp.costumer')),
            ],
        ),
        migrations.AddField(
            model_name='costumer',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loanapp.level'),
        ),
        migrations.AddField(
            model_name='costumer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Contactlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.JSONField()),
                ('costumer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='loanapp.costumer')),
            ],
        ),
        migrations.CreateModel(
            name='Bankdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bvn', models.CharField(blank=True, max_length=100, null=True)),
                ('debit_card', models.CharField(blank=True, max_length=100, null=True)),
                ('costumer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loanapp.costumer')),
            ],
        ),
    ]
