# Generated by Django 3.1.5 on 2021-02-26 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='phone',
        ),
        migrations.AddField(
            model_name='myuser',
            name='activate',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
