# Generated by Django 4.0.4 on 2022-08-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0002_alter_costumer_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='firstname',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='costumer',
            name='lastname',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
