# Generated by Django 4.0.4 on 2022-10-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0003_costumer_firstname_costumer_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Virtual_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='costumer',
            name='lga',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='costumer',
            name='state',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
