# Generated by Django 4.0.4 on 2022-10-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0004_virtual_account_costumer_lga_costumer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantor',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
