# Generated by Django 4.0.4 on 2022-10-09 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0005_guarantor_address_guarantor_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankdetail',
            old_name='debit_card',
            new_name='bank_name',
        ),
    ]
