# Generated by Django 4.0.4 on 2022-10-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0006_rename_debit_card_bankdetail_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetail',
            name='is_verify',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
