# Generated by Django 3.2.16 on 2023-01-12 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0006_alter_virtualaccount_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='today',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='today_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='loanapp.customer'),
        ),
        migrations.AlterField(
            model_name='virtualaccount',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_account', to='loanapp.customer'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='customerImage')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_name', to='loanapp.customer')),
            ],
        ),
    ]
