# Generated by Django 4.2.4 on 2023-11-26 11:00

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("loanapp", "0007_auto_20230112_1259"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="obj",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="data",
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name="paymentdata",
            name="data",
            field=jsonfield.fields.JSONField(),
        ),
    ]
