# Generated by Django 4.0.4 on 2022-10-20 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0008_alter_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtual_account',
            name='acc_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='virtual_account',
            name='costumer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loanapp.costumer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtual_account',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='virtual_account',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='virtual_account',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='contacts',
            field=models.JSONField(null=True),
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loanapp.loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('successful', models.BooleanField(default=False)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='loanapp.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=50, null=True)),
                ('acc_no', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('data', models.JSONField(null=True)),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loanapp.costumer')),
            ],
        ),
    ]
