# Generated by Django 4.0.4 on 2022-10-20 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0009_virtual_account_acc_no_virtual_account_costumer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='costumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loanapp.costumer'),
        ),
    ]
