# Generated by Django 3.2.16 on 2022-10-27 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0010_alter_loan_costumer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='acc_no',
            new_name='ref',
        ),
    ]
