# Generated by Django 3.2.16 on 2022-11-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0012_auto_20221028_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='rep',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='zubyuser',
            name='phone',
            field=models.CharField(max_length=100, unique=True, verbose_name='phone number'),
        ),
    ]
