# Generated by Django 3.2.16 on 2022-11-13 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0013_auto_20221112_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='collector_record',
        ),
    ]
