# Generated by Django 3.2.16 on 2022-11-13 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0014_remove_order_collector_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='loanapp.collector'),
        ),
    ]
