# Generated by Django 3.2.16 on 2022-11-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0015_order_collector'),
    ]

    operations = [
        migrations.AddField(
            model_name='zubyuser',
            name='is_collector',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.DeleteModel(
            name='CollectorRecord',
        ),
    ]
