# Generated by Django 3.2.16 on 2022-11-13 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0016_auto_20221113_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loanapp.collector'),
        ),
    ]
