# Generated by Django 3.2.16 on 2022-11-13 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0017_loan_collector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='loanapp.supervisor'),
        ),
    ]
