# Generated by Django 3.2.16 on 2022-11-15 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0018_alter_collector_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantor',
            name='costumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='loanapp.costumer'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='costumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='loanapp.costumer'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_type', models.CharField(max_length=20)),
                ('collection_object', models.CharField(max_length=20)),
                ('collection_contact', models.CharField(max_length=20)),
                ('collection_comment', models.TextField()),
                ('collection_status', models.CharField(max_length=20)),
                ('costumer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='loanapp.costumer')),
            ],
        ),
    ]
