# Generated by Django 3.2.16 on 2022-11-26 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0019_auto_20221115_0930'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Virtual_account',
            new_name='VirtualAccount',
        ),
        migrations.AddField(
            model_name='repayment',
            name='receive_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='loanapp.collector'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
