# Generated by Django 3.2.16 on 2022-11-27 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0020_auto_20221126_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='last_cashout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repayment',
            name='paid_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Cashout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
