# Generated by Django 3.2.16 on 2022-11-30 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0022_loan_last_share'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanPayment',
        ),
    ]
