# Generated by Django 3.2.16 on 2022-11-30 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0023_delete_loanpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=20, null=True)),
                ('id_from_method', models.IntegerField(default=0)),
                ('account_number', models.IntegerField(default=0)),
                ('bank_code', models.IntegerField(default=0)),
                ('full_name', models.IntegerField(default=0)),
                ('created_at', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('reference', models.IntegerField(default=0)),
                ('complete_message', models.IntegerField(default=0)),
                ('bank_name', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('successful', models.BooleanField(default=False)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='loanapp.loan')),
            ],
        ),
    ]
