# Generated by Django 3.2.16 on 2022-11-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0025_auto_20221130_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpayment',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
