# Generated by Django 3.2.16 on 2022-12-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0027_auto_20221130_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repayment',
            name='amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
